image: rhiananthony/dsde-toolbox:gitlab-runner-11.4.4

stages:
  - dev
  - test
  - staging
  - prod

deploy_lira_dev:
  tags:
    - green
  stage: dev
  script:
    - export LIRA_ENVIRONMENT=dev
    - bash gitlab/deploy_lira.sh

deploy_falcon_dev:
  tags:
    - green
  stage: dev
  script:
    - export LIRA_ENVIRONMENT=dev
    - bash gitlab/deploy_falcon.sh

deploy_lira_test:
  tags:
    - green
  stage: test
  script:
    - export LIRA_ENVIRONMENT=test
    - bash gitlab/deploy_lira.sh
  when: manual

deploy_falcon_test:
  tags:
    - green
  stage: test
  script:
    - export LIRA_ENVIRONMENT=test
    - bash gitlab/deploy_falcon.sh
  when: manual

deploy_lira_staging:
  tags:
    - green
  stage: staging
  script:
    - export LIRA_ENVIRONMENT=staging
    - bash gitlab/deploy_lira.sh
  when: manual

deploy_falcon_staging:
  tags:
    - green
  stage: staging
  script:
    - export LIRA_ENVIRONMENT=staging
    - bash gitlab/deploy_falcon.sh
  when: manual

deploy_lira_prod:
  tags:
    - green
  stage: prod
  script:
    - export LIRA_ENVIRONMENT=prod
    - bash gitlab/deploy_lira.sh
  when: manual

deploy_falcon_prod:
  tags:
    - green
  stage: prod
  script:
    - export LIRA_ENVIRONMENT=prod
    - bash gitlab/deploy_falcon.sh
  when: manual
