image: rhiananthony/dsde-toolbox:gitlab-runner-11.4.4

stages:
  - deploy

deploy_lira_dev:
  tags:
    - green
  stage: deploy
  script:
    - export ENVIRONMENT=dev
    - bash gitlab/deploy_lira.sh

deploy_falcon_dev:
  tags:
    - green
  stage: deploy
  script:
    - export ENVIRONMENT=dev
    - bash gitlab/deploy_falcon.sh
