image: rhiananthony/dsde-toolbox:gitlab-runner-11.4.4

stages:
  - deploy

deploy_lira_dev:
  tags:
    - green
  stage: deploy
  script:
    - export ENVIRONMENT=${BRANCH}
    - bash gitlab/test.sh

deploy_falcon_dev:
  tags:
    - green
  stage: deploy
  script:
    - export ENVIRONMENT=${BRANCH}
    - bash gitlab/test.sh

#deploy_lira_test:
#  tags:
#    - green
#  stage: test
#  script:
#    - export ENVIRONMENT=test
#    - bash gitlab/deploy_lira.sh
#  when: manual
#
#deploy_falcon_test:
#  tags:
#    - green
#  stage: test
#  script:
#    - export ENVIRONMENT=test
#    - bash gitlab/deploy_falcon.sh
#  when: manual
#
#deploy_lira_staging:
#  tags:
#    - green
#  stage: staging
#  script:
#    - export ENVIRONMENT=staging
#    - bash gitlab/deploy_lira.sh
#  when: manual
#
#deploy_falcon_staging:
#  tags:
#    - green
#  stage: staging
#  script:
#    - export ENVIRONMENT=staging
#    - bash gitlab/deploy_falcon.sh
#  when: manual
#
#deploy_lira_prod:
#  tags:
#    - green
#  stage: prod
#  script:
#    - export ENVIRONMENT=prod
#    - bash gitlab/deploy_lira.sh
#  when: manual
#
#deploy_falcon_prod:
#  tags:
#    - green
#  stage: prod
#  script:
#    - export ENVIRONMENT=prod
#    - bash gitlab/deploy_falcon.sh
#  when: manual

