image: rhiananthony/dsde-toolbox:gitlab-runner-11.4.4

stages:
  - deploy

variables:
  ENVIRONMENT: ${CI_BUILD_REF_NAME}

deploy_lira:
  stage: deploy
  script:
    - bash gitlab/deploy_lira.sh
  only:
    refs:
      - dev
      - ra_dev_cicd_deploy
      - test
      - integration
      - staging
  when: always

deploy_falcon:
  stage: deploy
  script:
    - bash gitlab/deploy_falcon.sh
  only:
    refs:
      - dev
      - test
      - integration
      - staging
  when: always
