version: 3

groups:
  pullapprove-admins:
    conditions:
      - "'.pullapprove.yml' in files"
    reviews:
      required: 1
    reviewers:
      users:
        - rhiananthony
      teams:
        - secops

  code-review:
    reviews:
      required: 1
    reviewers:
      users:
        - rhiananthony
      teams:
        - pipelines-team
