version: 3

groups:
  pullapprove-admins:
    conditions:
    - "'.pullapprove.yml' in files"

    reviews:
      required: 1
      author_value: 1 # if author in group reduce number of approvals needed by this number

    reviewers:
      users:
      - rhiananthony
      teams:
      - secops

  code-review:
    reviews:
      required: 1
      author_value: 1 # if author in group reduce number of approvals needed by this number
      request_order: shuffle  # reviewers will be chosen in a random order

    reviewers:
      users:
      - rhiananthony
      teams:
      - pipelines-team

#notifications:
#- when: pullapprove.approved
#  if: "author_association == 'CONTRIBUTOR'"
#  comment: "The review is completed. Thanks @{{ author }}."
